StorageApi/Models/StorageItem.cs
namespace StorageApi.Models
{
    public class StorageItem
    {
        public StorageItem(string itemName)
        {
            ItemName = itemName;
        }

        public int Id { get; set; }

        public string ItemName { get; private set; }

        public int ItemAmount { get; set; }
    }
}

StorageApi/Controllers/StorageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StorageApi.Exceptions;
using StorageApi.Interfaces;
using StorageApi.Models;

namespace StorageApi.Controllers
{
    public class StorageController : Controller
    {
        private IDataRepository _repository;

        public StorageController(IDataRepository repository)
        {
            _repository = repository;
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetItemCount(string id)
        {
            try
            {
                return Ok(await _repository.GetItemCountAsync(id));
            }
            catch (NotFoundException e)
            {
                return NotFound(e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddItemAmount(string id, int amountToAdd)
        {
            try
            {
                await _repository.AddItemAmountAsync(id, amountToAdd);
                return NoContent();
            }
            catch (NotFoundException e)
            {
                return NotFound(e.Message);
            }
            catch (FullStorageException e)
            {
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> RemoveItemAmount(string id, int amountToRemove)
        {
            try
            {
                await _repository.RemoveItemAmountAsync(id, amountToRemove);
                return NoContent();
            }
            catch (NotFoundException e)
            {
                return NotFound(e.Message);
            }
            catch (EmptyStorageException e)
            {
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddItemAmountToAll()
        {
            try
            {
                await _repository.AddItemAmountToAllAsync();
                return NoContent();
            }
            catch (FullStorageException e)
            {
                return BadRequest(e.Message);
            }
        }

        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetAllItemsAsync());
        }
    }
}

StorageApi/Controllers/StorageItemController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StorageApi.Exceptions;
using StorageApi.Interfaces;
using StorageApi.Models;

namespace StorageApi.Controllers
{
    
    [ApiController]
    [Route("api/[controller]")]
    public class StorageItemController : ControllerBase
    {
        private readonly IDataRepository _repository;

        public StorageItemController(IDataRepository repository)
        {
            _repository = repository;
        }

        [HttpPost]
        public async Task<IActionResult> RemoveMany(List<StorageItem> items)
        {
            try
            {
                await _repository.RemoveManyAsync(items);
                return NoContent();
            }
            catch (NotFoundException e)
            {
                return NotFound(e.Message);
            }
            catch (EmptyStorageException e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

StorageApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StorageApi/Views/Storage/Index.cshtml
@model IEnumerable<StorageApi.Models.StorageItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form method="post" action="@Url.Action("AddItemAmountToAll", "Storage")" onsubmit="setTimeout(function () { window.location.reload(); }, 100)">
    <input id="Addtoallsubmit" type="submit" value="Add 10 to all" />
</form>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemAmount) (Max 500)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemName)
            </td>
            <td id="@item.ItemName-current-amount">
                @Html.DisplayFor(modelItem => item.ItemAmount)
            </td>
            <td>
                <form method="post" action="@Url.Action("AddItemAmount", "Storage")" onsubmit="setTimeout(function () { window.location.reload(); }, 100)">
                    <input id="Add-@item.ItemName-name" name="id" value="@item.ItemName" type="hidden" />
                    <input id="Add-@item.ItemName-amount" type="number" name="amountToAdd" min="0" max="500" />
                    <input id="Add-@item.ItemName-submit" type="submit" value="Add item/s" />
                </form>
                <form method="post" action="@Url.Action("RemoveItemAmount", "Storage")" onsubmit="setTimeout(function () { window.location.reload(); }, 100)">
                    <input id="Remove-@item.ItemName-name" name="id" value="@item.ItemName" type="hidden" />
                    <input id="Remove-@item.ItemName-amount" type="number" name="amountToRemove" min="0" max="500" />
                    <input id="Remove-@item.ItemName-submit" type="submit" value="Remove item/s" />
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>